# Generated by Django 5.2.7 on 2025-10-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Sách', 'verbose_name_plural': 'Sách'},
        ),
        migrations.AlterModelOptions(
            name='bookimage',
            options={'verbose_name': 'Hình Ảnh Sách', 'verbose_name_plural': 'Hình Ảnh Sách'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh Mục', 'verbose_name_plural': 'Danh Mục'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='bookimage',
            table='book_image',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
