# Generated by Django 5.2.7 on 2025-10-13 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_options_alter_customer_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Khách Hàng', 'verbose_name_plural': 'Khách Hàng'},
        ),
    ]
