# Generated by Django 5.2.7 on 2025-10-13 03:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_alter_book_options_alter_bookimage_options_and_more'),
        ('customer', '0003_alter_customer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐ 1 - Rất tệ'), (2, '⭐⭐ 2 - Tệ'), (3, '⭐⭐⭐ 3 - Bình thường'), (4, '⭐⭐⭐⭐ 4 - Tốt'), (5, '⭐⭐⭐⭐⭐ 5 - Xuất sắc')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='book.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Đánh Giá',
                'verbose_name_plural': 'Đánh Giá Sách',
                'db_table': 'review',
                'ordering': ['-created_at'],
            },
        ),
    ]
